### ISSUE TITLE
Notification not working as expected at certain time

### ISSUE THREAD

**Issue by tiwwwi** [gdelataillade/alarm#19] opened 2023-03-18 14:57 UTC
Thats a funny one.. nearly pulled out whats left of my hair  last night.  Coudn't understand why suddenly the notifications were not working anymore both in emulator and physical phone.  Alarm sound still rings  but  the notifications don't display.  Then I woke up this morning, started testing and everything was working.  To reproduce I used the android  emulator.  In System -> Date & Time, disable "Set time automatically" then under time  set the time to a time between  8pm and 11:59pm.   Run the app with a notification,  notifications don't display.

**Comment by gdelataillade** [comment] 2023-03-18 17:47
It looks like it's an issue related to how the package handles time zones. I'll take a close look at it. Thank you for your message.

**Comment by tiwwwi** [comment] 2023-03-26 23:07
when manually changed?  it actually doesn't work for me between 8pm and 11:59pm  without changing the time manually.  Changing the time manually was just a step to reproduce without having to wait for that time frame to test.

**Comment by gdelataillade** [comment] 2023-03-27 03:32
Sorry @tiwwwi I guess I didn't understand well your issue...

In debug mode, are you able to see the Alarm logs ? Can you tell me what is the log you have when you schedule the alarm ? It can really help me. It should be something like this:

`[Alarm] Notification with id $id scheduled successfuly at $zdt`

`zdt` is the date and time the notification is scheduled in the Zulu timezone (GMT).

**Comment by tiwwwi** [comment] 2023-03-27 04:22
at a working time:
==================
# flutter run | grep Alarm
I/FlutterBackgroundExecutor( 6558): Starting AlarmService...
I/flutter ( 6558): [Alarm] Notification with id 48 canceled
I/flutter ( 6558): [Alarm] NotificationOnKillService set with success
I/flutter ( 6558): [Alarm] Notification with id 48 scheduled successfuly at 2023-03-27 04:14:50.000Z
I/flutter ( 6558): [Alarm] ring
I/flutter ( 6558): [Alarm] Alarm fadeDuration: {assetAudioPath: assets/audio/zedd.mp3, loopAudio: false, fadeDuration: 0}
I/flutter ( 6558): [Alarm] Alarm with id 48 starts playing.

at a not working:
==================
# flutter run | grep Alarm
I/FlutterBackgroundExecutor( 7450): Starting AlarmService...
I/flutter ( 7450): [Alarm] Notification with id 48 canceled
I/flutter ( 7450): [Alarm] NotificationOnKillService set with success
I/flutter ( 7450): [Alarm] Notification with id 48 scheduled successfuly at 2023-03-29 02:16:31.000Z
I/flutter ( 7450): [Alarm] ring
I/flutter ( 7450): [Alarm] Alarm fadeDuration: {assetAudioPath: assets/audio/zedd.mp3, loopAudio: false, fadeDuration: 0}
I/flutter ( 7450): [Alarm] Alarm with id 48 starts playing.

**Comment by tiwwwi** [comment] 2023-03-27 04:23
no difference in the logs when set to a working hours vs not working hours.   You can't replicate my issue?

**Comment by gdelataillade** [comment] 2023-03-28 06:17
I was able to reproduce your issue ! Fixing it is now my top priority. I'll let you know when it's done.

**Comment by gdelataillade** [comment] 2023-03-28 07:05
Hey @tiwwwi 

I think I fixed the issue. Here are the changes I made:
https://github.com/gdelataillade/alarm/commit/6276b15a43104cf5a73f35a42fe3c1940b4d48d7#diff-bd754698c3da7e10df0d984e8c571502d2a7a7bf20e2c1b56d1949b6a9551d7e

Please update the alarm dependency to `0.2.4` and tell me if you still have the issue.

**Comment by tiwwwi** [comment] 2023-03-28 21:18
I confirm!  it works!!!!

**Comment by gdelataillade** [comment] 2023-03-29 03:17
I'm closing this issue then. Thank you very much for your help !

**Closed** 2023-03-29 03:17 UTC
Labels: bug, question
