### ISSUE TITLE
Setting an alarm causes native crash

### ISSUE THREAD

**Issue by KonstantinRr** [gdelataillade/alarm#18] opened 2023-03-16 17:12 UTC
Hey, I got the following issue after setting an alarm. It crashed our app.
The issue only happened once so it wasn’t possible to reproduce it. Setting the alarm worked just fine in all other cases with the same parameters.

Tested on `^0.1.4`

```
[ServiceAlarm] [2023-03-16T15:28:51.031856+01:00}] [INFO]: Setting system alarm assets/alarm_sounds/Aura.mp3 at 2023-03-16 00:05:00.000
alarm/SwiftAlarmPlugin.swift:19: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSOSStatusErrorDomain Code=561015905 "Session activation failed" UserInfo={NSLocalizedDescription=Session activation failed}
alarm/SwiftAlarmPlugin.swift:19: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSOSStatusErrorDomain Code=561015905 "Session activation failed" UserInfo={NSLocalizedDescription=Session activation failed}
* thread #4, queue = 'com.apple.root.default-qos', stop reason = Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSOSStatusErrorDomain Code=561015905 "Session activation failed" UserInfo={NSLocalizedDescription=Session activation failed}
    frame #0: 0x00000001a1c3c0f8 libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`:
->  0x1a1c3c0f8 <+0>: ret
libswiftCore.dylib`:
    0x1a1c3c0fc <+0>: b      0x1a1c3c0f8               ; _swift_runtime_on_report
libswiftCore.dylib`:
    0x1a1c3c100 <+0>: adrp   x8, 366305
    0x1a1c3c104 <+4>: ldrb   w0, [x8, #0xabc]
Target 0: (Runner) stopped.
Lost connection to device.
```

Here is the flutter doctor
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.2.1 22D68 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.76.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by gdelataillade** [comment] 2023-03-16 17:30
Hi @KonstantinRr 

Thanks for your interest in the package.

I just published the `0.2.0` version of the package including a big refactoring. A lot of things have been updated so I think your issue should be fixed in this version.

Please update the package to the latest version and let me know if you encounter the same issue.

Best regards

**Comment by GaelleJoubert** [comment] 2023-03-27 07:39
I tested it with the version 0.2.6 and I have the same issue on IOS. I am gonna dig a little bit to find the cause.

**Comment by KonstantinRr** [comment] 2023-03-28 10:47
Hi, Thanks for the update! I tested it for the last week with `0.2.0` and never encountered the issue again. I will keep this thread updated if it ever happens again.

**Comment by gdelataillade** [comment] 2023-03-29 04:42
Great! Well, the issue seems to be fixed, so I'm closing it.

If you encounter the issue again, please open another issue and mention this one.

**Closed by gdelataillade** 2023-03-29 04:42 UTC
Labels: bug, question
