### ISSUE TITLE
iOS App Crash when init Alarm.

### ISSUE THREAD

**Issue by iSaqibShafique** [gdelataillade/alarm#209] opened 2024-06-04 15:37 UTC
**Alarm plugin version**
3.1.4

**Describe the bug**
When I do initialize the Alarm in main() and trying running app on Simulator, it start crashing.

**To Reproduce**
*Steps to reproduce the behavior:*
1. *...*

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Device info**
Simulator iPhone 12 mini.
iOS 17.4

**Additional context**
*Add any other context about the problem here.*

**Comment by gdelataillade** [comment] 2024-06-05 10:11
Hi @iSaqibShafique 

Make sure you followed the installation steps in the README. Also you should use the `await` keyword every time you call a method from `Alarm` class. Please let me know if it fixes your crash.

**Comment by North101** [comment] 2024-06-19 19:36
I am also having this happen on iOS when doing a hot reload with multiple alarms set, and also in general when multiple alarms are set in succession (with each being `await`ed). My fix has been to add a delay of 100ms after each `Alarm.set` call in my app, but I obviously can't do this within `Alarm.init`.

**Comment by BaoTrung37** [comment] 2024-07-25 07:52
I still have same issue

**Comment by gdelataillade** [comment] 2024-08-02 16:46
Hi guys,

Some recommendations:
- make sure you call `Alarm.init` just once
- don't directly use `AlarmStorage`
- use `await` for all alarm operations

**Comment by North101** [comment] 2024-08-04 01:58
I am doing all of those things and yet it still causes crashes on iOS. Specifically when scheduling multiple alarms in a row (each of which is awaited). I have been able to reduce the chance of crashes during runtime by putting a delay of 100ms between each scheduled alarm. However it also crashes every time I hot reload

**Comment by BaoTrung37** [comment] 2024-08-05 07:30
@North101 You can folk the project and fix the code below. The app is not crash.
![image](https://github.com/user-attachments/assets/273d1198-40f8-4095-83bd-faeaee35a10a)

**Comment by gdelataillade** [comment] 2024-10-17 14:43
I'm closing this issue because in the meantime version `4.0.0` was released including a significant refactoring of the code and many bug fixes. Feel free to reopen if needed.

**Closed by gdelataillade** 2024-10-17 14:43 UTC
Labels: bug

**Comment by North101** [comment] 2024-10-17 19:33
I can confirm that the latest version fixes the crashes
